## 개발환경
#
#spring:
#  h2:
#    console:
#      enabled: true
#
#  # H2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/dummy_schema;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create  # create or validate
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#
#---
#
## 배포환경
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#  # MySQL
#  datasource:
#    url: jdbc:mysql://??/??
#    username:
#    password:
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create  # create or validate
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
