package com.armand.ourhome.domain.item;

public enum Category {
  FURNITURE, FABRIC, LIGHT, HOME_APPLIANCE, KITCHEN_UTENSIL,
  DECORATION, STORAGE_CLOSET, DAILY_SUPPLIES, DAILY_NECESSITIES,
  TOOL, ETC;
}
