spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # sequence 전략 default 해제
  jpa:
    hibernate:
      use-new-id-generator-mappings: false