server:
  port: 8082
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create  # create or validate
    show-sql: true
    properties:
      hibernate.format_sql: true
